### ISSUE TITLE
User canceled the requestDevice() chooser

### ISSUE THREAD

**Issue by shammond42** [foundryvtt/pixels#4]
I am seeing this error message when I click the "Add Pixel Dice" button.

NotFoundError: User canceled the requestDevice() chooser.

This happen when running the foundry application or using Chrome. It also happens on both Windows and Mac. The version of foundry in use is Version 11 Stable, build 315.

**Comment by ShadowDrakken** [comment]
Same, Foundry v11.315, Unfulfilled Rolls v0.1.4, Pixels v0.1.0

**Comment by CodyNguyen235** [comment]
Is there any further development regarding this issue? Or has the project been abandoned?

**Comment by CodyNguyen235** [comment]
Is there any more information regarding this issue? I noticed there hasn't been an update to this module since February. Tested on Foundry v12 Application and it appears to still be occurring.

**Comment by NonchalantWombat** [comment]
Commenting to give visibility; same issue, not working in V12 for me (on V0.2.0)

**Comment by 181raven** [comment]
Same issue persisting here, trying to bump for visibility

**Comment by blalasaadri** [comment]
**Disclaimer:** I'm not in any way connected to the development of this integration, but I have seen this problem before.

The integration won't work in the desktop app, because the desktop app does not implement a Bluetooth device selection screen. It will _only_ work in a Chromium based browser that has WebBluetooth enabled. (You can check [caniuse.com](https://caniuse.com/web-bluetooth) for many browsers.)
This is something that Foundry could in theory change by implementing a selection screen, but it's not an issue with this integration.

WebBluetooth also requires an HTTPS connection, which means it needs an SSL certificate. There is a tutorial on how to install that certificate [here](https://foundryvtt.com/article/ssl/). It _can_ be a self-signed certificate though. (You will get warnings about the certificate being self-signed, but that's OK.)
This is something required by the Web Bluetooth API (as mentioned, though not explained in detail, [in this entry in the mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API#security_considerations)) for security reasons, so there's nothing the devs behind this integration or Foundry as a whole can realistically do about it.

If either of these conditions is **not** met, you will certainly get the reported error message. If anyone is having this issue despite meeting both requirements though, that would surely be useful to know for the devs.

**Comment by ShadowDrakken** [comment]
Thing is, Foundry uses Electron, which is a Chromium based wrapper so it SHOULD support WebBluetooth.

That aside, a solution would be to break out of Electron for the desktop client and hook into bluetooth natively. Doesn't solve the issue for non-supported browsers, but fixes it for the host app at least.

**Comment by blalasaadri** [comment]
> Thing is, Foundry uses Electron, which is a Chromium based wrapper so it SHOULD support WebBluetooth.

Electron _does_ support WebBluetooth. It just doesn't have a pre-existing Bluetooth device selection window. Which is why the error described here is shown.
If one were to build that kind of selector, it would work. But that's something that would have to be built as part of Foundry, I don't think this integration can reasonably do that.
